# Phase 3 - File Handling & Data Cleaning


## 3.1 File Handling and Summary

This section uses Python's csv module to read the Iris dataset and calculate basic statistics, including the total number of flowers, minimum values, maximum values, and averages.

In [12]:
# Import the csv module to read the Iris dataset.

import csv

# Open the iris.data file and store its contents in a list.

with open("iris.data", "r") as file:
    reader = csv.reader(file)
    data = [row for row in reader if row]

# Print the total number of flowers and the first five rows to get a quick look at the data.

print("Total number of flowers:", len(data))

for row in data[:5]:
    print(row)

Total number of flowers: 150
['5.1', '3.5', '1.4', '0.2', 'Iris-setosa']
['4.9', '3.0', '1.4', '0.2', 'Iris-setosa']
['4.7', '3.2', '1.3', '0.2', 'Iris-setosa']
['4.6', '3.1', '1.5', '0.2', 'Iris-setosa']
['5.0', '3.6', '1.4', '0.2', 'Iris-setosa']

In [13]:
# Go through the four flower measurements and calculate the minimum, maximum, and average for each.

columns = [
    "Sepal Length",
    "Sepal Width",
    "Petal Length",
    "Petal Width"
]

summary = []

for i in range(4):
    values = [float(row[i]) for row in data]

    minimum = min(values)
    maximum = max(values)
    average = sum(values) / len(values)

    summary.append(
        f"{columns[i]}:\n"
        f"  Minimum: {minimum:.2f}\n"
        f"  Maximum: {maximum:.2f}\n"
        f"  Average: {average:.2f}\n"
    )


# Save the results and total number of flowers in a summary.txt file.

with open("summary.txt", "w") as file:
    file.write(f"Total Rows: {len(data)}\n\n")
    file.write("\n".join(summary))

print("summary.txt created successfully!")


# Print the summary to check that everything was calculated and saved correctly.

print("\nIRIS DATASET SUMMARY")
print("Total Rows:", len(data))
print()

for result in summary:
    print(result)

summary.txt created successfully!

IRIS DATASET SUMMARY
Total Rows: 150

Sepal Length:
  Minimum: 4.30
  Maximum: 7.90
  Average: 5.84

Sepal Width:
  Minimum: 2.00
  Maximum: 4.40
  Average: 3.05

Petal Length:
  Minimum: 1.00
  Maximum: 6.90
  Average: 3.76

Petal Width:
  Minimum: 0.10
  Maximum: 2.50
  Average: 1.20

## 3.2 Data Inspection

In this section, we use pandas to load the Iris dataset and take a closer look at the data. We check the column names, data types, and missing values to see if anything needs to be fixed before cleaning.

In [14]:
import pandas as pd

# Add column names since the original file has none
column_names = [
    "sepal_length",
    "sepal_width",
    "petal_length",
    "petal_width",
    "species"
]

# Load the Iris dataset
df = pd.read_csv("iris.data", header=None, names=column_names)

# Show the first five rows
print("First five rows of the dataset:")
display(df.head())

First five rows of the dataset:

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [15]:
# Check the column names
print("Column Names:")
print(df.columns.tolist())

# Check the data type of each column
print("\nData Types:")
print(df.dtypes)

Column Names:
['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

Data Types:
sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

In [16]:
# Check for missing values in each column
print("Missing Values:")
print(df.isnull().sum())

# Check the number of rows and columns
print("\nDataset Shape:")
print(df.shape)

Missing Values:
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

Dataset Shape:
(150, 5)

### Data Inspection Findings

The Iris dataset contains 150 rows and 5 columns. Four columns contain numerical measurements, while the species column identifies the flower type.

We found no missing values, and the data types are appropriate for the information stored in each column. The dataset appears to be in good condition for cleaning and further analysis.

## 3.3 Data Cleaning and Export

In this section, we check for duplicate records and missing values before cleaning the dataset. We will keep all 150 flower observations, since identical measurements do not necessarily mean the records are incorrect. Finally, we will save the cleaned dataset as a new CSV file.

In [18]:
# Check for duplicate rows
print("Duplicate Rows:", df.duplicated().sum())

# Check for missing values
print("\nMissing Values:")
print(df.isnull().sum())

Duplicate Rows: 3

Missing Values:
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [19]:
# Make a copy so the original data stays unchanged
df_cleaned = df.copy()

# Remove rows with missing values, if any
df_cleaned = df_cleaned.dropna()

# Remove extra spaces from species names
df_cleaned["species"] = df_cleaned["species"].str.strip()

# Check duplicates without removing them
print("Duplicate Rows:", df_cleaned.duplicated().sum())

print("Data cleaning completed!")

Duplicate Rows: 3
Data cleaning completed!

In [20]:
# Compare the original and cleaned datasets
print("Original Rows:", len(df))
print("Cleaned Rows:", len(df_cleaned))

# Check for any remaining missing values
print("\nRemaining Missing Values:")
print(df_cleaned.isnull().sum())

# Check the data types
print("\nData Types:")
print(df_cleaned.dtypes)

# Preview the cleaned data
print("\nCleaned Dataset Preview:")
display(df_cleaned.head())

Original Rows: 150
Cleaned Rows: 150

Remaining Missing Values:
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

Data Types:
sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

Cleaned Dataset Preview:

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [21]:
# Save the cleaned dataset as a CSV file
df_cleaned.to_csv("iris_cleaned.csv", index=False)

print("iris_cleaned.csv saved successfully!")

iris_cleaned.csv saved successfully!

In [22]:
# Read the saved CSV file to make sure it worked
verified_df = pd.read_csv("iris_cleaned.csv")

# Check the number of rows and columns
print("Exported Rows:", len(verified_df))
print("Exported Columns:", len(verified_df.columns))

# Show the first five rows
display(verified_df.head())

Exported Rows: 150
Exported Columns: 5

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

### Data Cleaning Summary

We checked the Iris dataset for missing values, duplicate records, and data types. No missing values were found, but we identified three duplicate records. We decided to keep them because flowers can have identical measurements without being the same observation.

We also checked the species names for extra spaces and saved the cleaned dataset as iris_cleaned.csv. All 150 observations were preserved for the next phase of the project.